theme: jekyll-theme-primer
title: Recommender systems
description: Recommend the best restaurants!
baseurl:
markdown: kramdown
kramdown:
    math_engine: mathjax
    input: GFM
    syntax_highlighter: rouge
